<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Coupon;
use Illuminate\Database\Seeder;

class PromotionSeeder extends Seeder
{
    /**
     * Seed 10 discount codes for the admin "Promotions & Campaigns" screen.
     *
     * The screen reads `Coupon` through PromotionController — not the older
     * `Promotion` model, which is no longer wired to any admin route. Column
     * names here follow the coupons table: the amount is `value`, the window
     * closes at `expires_at`, and `type` is constrained by a CHECK to exactly
     * 'percentage' or 'fixed'.
     *
     * The set covers every status the list derives in `promotionFromApi`
     * (see `src/services/promotions.js` in the frontend): active, paused via
     * `is_active`, expired by `expires_at`, and expired by usage cap — plus
     * open-ended and uncapped rows, and one with no banner so the gradient
     * fallback has something to show.
     *
     * Idempotent: re-running updates the row for a code rather than stacking
     * duplicates or tripping the unique index.
     */
    public function run(): void
    {
        Coupon::withTrashed()->forceDelete();

        foreach ($this->promotions() as $promotion) {
            Coupon::updateOrCreate(
                ['code' => $promotion['code']],
                [
                    'name' => $promotion['name'],
                    'description' => $promotion['description'],
                    'banner_image' => $promotion['banner_image'],
                    'kind' => $promotion['kind'],
                    'type' => $promotion['type'],
                    'value' => $promotion['value'],
                    'min_order_amount' => $promotion['min_order_amount'],
                    'max_discount_amount' => $promotion['max_discount_amount'] ?? null,
                    'starts_at' => $promotion['starts_at'],
                    'expires_at' => $promotion['expires_at'],
                    'usage_limit' => $promotion['usage_limit'],
                    'user_limit' => $promotion['user_limit'],
                    'used_count' => $promotion['used_count'],
                    'is_active' => $promotion['is_active'],
                ]
            );
        }
    }

    /**
     * Real computer-store themed banner images so each promotion visually matches
     * the storefront catalog and product categories.
     */
    private function banner(string $seed): string
    {
        $images = [
            'bekie-rtx4070' => 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1600&q=80',
            'bekie-laptop-save25' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1600&q=80',
            'bekie-ship-monitor' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1600&q=80',
            'bekie-gamer-pc' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1600&q=80',
            'bekie-ssd-clearance' => 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1600&q=80',
            'bekie-ram-flash' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80',
            'bekie-vip-workstation' => 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1600&q=80',
            'bekie-weekend-monitor' => 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1600&q=80',
            'bekie-desk-set' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80',
            'bekie-gaming-setup' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80',
            'bekie-student-lap' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=80',
            'bekie-ship-pc' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1600&q=80',
            'bekie-starter-pc' => 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1600&q=80',
            'bekie-trade-pc' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1600&q=80',
            'bekie-memory-storage' => 'https://images.unsplash.com/photo-1555618568-8016a3d4c07c?auto=format&fit=crop&w=1600&q=80',
            'bekie-accessory-gift' => 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1600&q=80',
            'bekie-b2g1-accessory' => 'https://images.unsplash.com/photo-1589254065909-b7086229d08c?auto=format&fit=crop&w=1600&q=80',
            'bekie-audio-peripherals' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1600&q=80',
            'bekie-weekend-pc' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1600&q=80',
        ];

        return $images[$seed] ?? 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80';
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function promotions(): array
    {
        return [
            [
                'name' => 'RTX 4070 Launch Deal',
                'code' => 'RTX4070LAUNCH',
                'kind' => 'flash_sale',
                'description' => '15% off NVIDIA RTX 4070 gaming desktops and GPU builds.',
                'banner_image' => $this->banner('bekie-rtx4070'),
                'type' => 'percentage',
                'value' => 15.00,
                'min_order_amount' => 800.00,
                'max_discount_amount' => 220.00,
                'starts_at' => now()->subDays(4),
                'expires_at' => now()->addDays(6),
                'usage_limit' => 220,
                'user_limit' => 1,
                'used_count' => 164,
                'is_active' => true,
            ],
            [
                'name' => 'Laptop Upgrade Bonus',
                'code' => 'LAPTOPSAVE25',
                'kind' => 'bundle',
                'description' => 'Save $25 on gaming laptops, ultrabooks, and workstation upgrades.',
                'banner_image' => $this->banner('bekie-laptop-save25'),
                'type' => 'fixed',
                'value' => 25.00,
                'min_order_amount' => 600.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(18),
                'expires_at' => now()->addDays(32),
                'usage_limit' => 500,
                'user_limit' => 2,
                'used_count' => 138,
                'is_active' => true,
            ],
            [
                'name' => 'Monitor Delivery Saver',
                'code' => 'SHIPMONITOR',
                'kind' => 'free_shipping',
                'description' => 'Free delivery for 4K monitors, gaming displays, and desktop accessories.',
                'banner_image' => $this->banner('bekie-ship-monitor'),
                'type' => 'fixed',
                'value' => 9.99,
                'min_order_amount' => 120.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(30),
                'expires_at' => null,
                'usage_limit' => null,
                'user_limit' => null,
                'used_count' => 760,
                'is_active' => true,
            ],
            [
                'name' => 'Gaming PC Combo Deal',
                'code' => 'GAMERPC15',
                'kind' => 'bundle',
                'description' => '15% off gaming desktops, GPU bundles, and RGB premium kits.',
                'banner_image' => $this->banner('bekie-gamer-pc'),
                'type' => 'percentage',
                'value' => 15.00,
                'min_order_amount' => 900.00,
                'max_discount_amount' => 180.00,
                'starts_at' => now()->subDays(12),
                'expires_at' => now()->addDays(18),
                'usage_limit' => 280,
                'user_limit' => 1,
                'used_count' => 93,
                'is_active' => true,
            ],
            [
                'name' => 'Custom PC Build Promo',
                'code' => 'PCBUILD20',
                'kind' => 'bundle',
                'description' => '20% off custom desktop builds with motherboard, RAM, and SSD combos.',
                'banner_image' => null,
                'type' => 'percentage',
                'value' => 20.00,
                'min_order_amount' => 1000.00,
                'max_discount_amount' => 350.00,
                'starts_at' => now()->subDays(8),
                'expires_at' => now()->addDays(210),
                'usage_limit' => 1800,
                'user_limit' => 1,
                'used_count' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'SSD Summer Clearance',
                'code' => 'SSDSUMMER50',
                'kind' => 'flash_sale',
                'description' => '50% off NVMe SSD and storage upgrades during the clearance run.',
                'banner_image' => $this->banner('bekie-ssd-clearance'),
                'type' => 'percentage',
                'value' => 50.00,
                'min_order_amount' => 150.00,
                'max_discount_amount' => 260.00,
                'starts_at' => now()->subDays(80),
                'expires_at' => now()->subDays(15),
                'usage_limit' => null,
                'user_limit' => null,
                'used_count' => 570,
                'is_active' => true,
            ],
            [
                'name' => '24-Hour RAM Flash Sale',
                'code' => 'RAMFLASH24',
                'kind' => 'flash_sale',
                'description' => '20% off DDR5 RAM kits and memory upgrades for a limited 24 hours.',
                'banner_image' => $this->banner('bekie-ram-flash'),
                'type' => 'percentage',
                'value' => 20.00,
                'min_order_amount' => 160.00,
                'max_discount_amount' => 150.00,
                'starts_at' => now()->subDays(5),
                'expires_at' => now()->subDays(3),
                'usage_limit' => 120,
                'user_limit' => 1,
                'used_count' => 120,
                'is_active' => true,
            ],
            [
                'name' => 'VIP Workstation Upgrade',
                'code' => 'VIPWORK100',
                'kind' => 'free_gift',
                'description' => 'VIP members receive $100 off premium workstation and creator PC orders.',
                'banner_image' => $this->banner('bekie-vip-workstation'),
                'type' => 'fixed',
                'value' => 100.00,
                'min_order_amount' => 1500.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(90),
                'expires_at' => null,
                'usage_limit' => 40,
                'user_limit' => 1,
                'used_count' => 40,
                'is_active' => true,
            ],
            [
                'name' => 'Weekend Monitor Drop',
                'code' => 'WEEKENDMON15',
                'kind' => 'flash_sale',
                'description' => '15% off gaming monitors, office displays, and ultrawide setups.',
                'banner_image' => $this->banner('bekie-weekend-monitor'),
                'type' => 'percentage',
                'value' => 15.00,
                'min_order_amount' => 250.00,
                'max_discount_amount' => 200.00,
                'starts_at' => now()->subDays(2),
                'expires_at' => now()->addDays(4),
                'usage_limit' => 320,
                'user_limit' => 1,
                'used_count' => 228,
                'is_active' => true,
            ],
            [
                'name' => 'Office Desk Setup Bundle',
                'code' => 'DESKSET40',
                'kind' => 'bundle',
                'description' => '40% off monitor, keyboard, mouse, and desk accessory bundles.',
                'banner_image' => $this->banner('bekie-desk-set'),
                'type' => 'percentage',
                'value' => 40.00,
                'min_order_amount' => 500.00,
                'max_discount_amount' => 350.00,
                'starts_at' => now()->subDays(18),
                'expires_at' => now()->addDays(28),
                'usage_limit' => 210,
                'user_limit' => 2,
                'used_count' => 119,
                'is_active' => true,
            ],
            [
                'name' => 'Gaming Setup Bundle Bonus',
                'code' => 'GAMESYSTEM150',
                'kind' => 'bogo',
                'description' => 'Get $150 off complete gaming setups with a gaming PC and accessories.',
                'banner_image' => $this->banner('bekie-gaming-setup'),
                'type' => 'fixed',
                'value' => 150.00,
                'min_order_amount' => 1600.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(15),
                'expires_at' => now()->addDays(52),
                'usage_limit' => 180,
                'user_limit' => 1,
                'used_count' => 82,
                'is_active' => true,
            ],
            [
                'name' => 'Student Laptop Savings',
                'code' => 'STUDENTLAP18',
                'kind' => 'bundle',
                'description' => '18% off student laptops, accessories, and productivity bundles.',
                'banner_image' => $this->banner('bekie-student-lap'),
                'type' => 'percentage',
                'value' => 18.00,
                'min_order_amount' => 450.00,
                'max_discount_amount' => 200.00,
                'starts_at' => now()->subDays(35),
                'expires_at' => now()->addDays(65),
                'usage_limit' => 520,
                'user_limit' => 1,
                'used_count' => 190,
                'is_active' => true,
            ],
            [
                'name' => 'Desktop Delivery Deal',
                'code' => 'SHIPPC150',
                'kind' => 'free_shipping',
                'description' => 'Enjoy free shipping on desktop PCs, towers, and workstation upgrades.',
                'banner_image' => $this->banner('bekie-ship-pc'),
                'type' => 'fixed',
                'value' => 12.00,
                'min_order_amount' => 150.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(10),
                'expires_at' => now()->addDays(90),
                'usage_limit' => null,
                'user_limit' => null,
                'used_count' => 624,
                'is_active' => true,
            ],
            [
                'name' => 'Starter PC Kit Offer',
                'code' => 'STARTERPC30',
                'kind' => 'bundle',
                'description' => '$30 off starter PC kits with monitor, keyboard, and mouse bundles.',
                'banner_image' => $this->banner('bekie-starter-pc'),
                'type' => 'fixed',
                'value' => 30.00,
                'min_order_amount' => 300.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(7),
                'expires_at' => now()->addDays(12),
                'usage_limit' => 380,
                'user_limit' => 1,
                'used_count' => 116,
                'is_active' => true,
            ],
            [
                'name' => 'Trade-In Desktop Bonus',
                'code' => 'TRADEPC75',
                'kind' => 'free_gift',
                'description' => 'Upgrade your old desktop or laptop with $75 off eligible replacements.',
                'banner_image' => $this->banner('bekie-trade-pc'),
                'type' => 'fixed',
                'value' => 75.00,
                'min_order_amount' => 900.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(25),
                'expires_at' => now()->addDays(72),
                'usage_limit' => 110,
                'user_limit' => 1,
                'used_count' => 61,
                'is_active' => true,
            ],
            [
                'name' => 'Memory & Storage Upgrade',
                'code' => 'RAMSTORAGE12',
                'kind' => 'bundle',
                'description' => '12% off RAM and SSD upgrades for gaming desktops and workstations.',
                'banner_image' => $this->banner('bekie-memory-storage'),
                'type' => 'percentage',
                'value' => 12.00,
                'min_order_amount' => 200.00,
                'max_discount_amount' => 140.00,
                'starts_at' => now()->subDays(30),
                'expires_at' => now()->addDays(26),
                'usage_limit' => 500,
                'user_limit' => 2,
                'used_count' => 316,
                'is_active' => true,
            ],
            [
                'name' => 'Accessory Gift with Purchase',
                'code' => 'GIFTACCESSORY',
                'kind' => 'free_gift',
                'description' => 'Receive a bonus accessory pack with premium keyboard, mouse, or headset orders.',
                'banner_image' => $this->banner('bekie-accessory-gift'),
                'type' => 'fixed',
                'value' => 0.00,
                'min_order_amount' => 700.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(45),
                'expires_at' => now()->addDays(85),
                'usage_limit' => 260,
                'user_limit' => 1,
                'used_count' => 176,
                'is_active' => true,
            ],
            [
                'name' => 'Buy 2 Get 1 Accessory',
                'code' => 'B2G1ACCESS',
                'kind' => 'bogo',
                'description' => 'Buy two PC accessories and get a third one at a special price.',
                'banner_image' => $this->banner('bekie-b2g1-accessory'),
                'type' => 'fixed',
                'value' => 29.99,
                'min_order_amount' => 220.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(12),
                'expires_at' => now()->addDays(55),
                'usage_limit' => 240,
                'user_limit' => 1,
                'used_count' => 147,
                'is_active' => true,
            ],
            [
                'name' => 'Audio & Peripherals Bundle',
                'code' => 'PERIPH25',
                'kind' => 'bundle',
                'description' => '25% off audio gear, keyboards, headsets, and premium desk accessories.',
                'banner_image' => $this->banner('bekie-audio-peripherals'),
                'type' => 'percentage',
                'value' => 25.00,
                'min_order_amount' => 180.00,
                'max_discount_amount' => 220.00,
                'starts_at' => now()->subDays(6),
                'expires_at' => now()->addDays(22),
                'usage_limit' => 160,
                'user_limit' => 1,
                'used_count' => 89,
                'is_active' => true,
            ],
            [
                'name' => 'Weekend Desktop Delivery',
                'code' => 'WEEKENDPC',
                'kind' => 'free_shipping',
                'description' => 'Free delivery for desktop computers and all-in-one PC orders placed this weekend.',
                'banner_image' => $this->banner('bekie-weekend-pc'),
                'type' => 'fixed',
                'value' => 15.00,
                'min_order_amount' => 0.00,
                'max_discount_amount' => null,
                'starts_at' => now()->subDays(3),
                'expires_at' => now()->addDays(5),
                'usage_limit' => 600,
                'user_limit' => 1,
                'used_count' => 230,
                'is_active' => true,
            ],
        ];
    }
}
