server {
    # Render provides the PORT environment variable
    listen ${PORT:-8080};
    server_name _;
    root /var/www/html/public;
    index index.php;

    # Block access to .php files in the /public/build directory
    location ~ /build/.*\.php$ {
        deny all;
    }

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
