<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Promote `products.uuid` to the table's primary key.
 *
 * Previously `products` kept an auto-increment integer `id` as its primary key
 * and used `uuid` only for route binding. This migration makes the UUID the real
 * key — auto-generated by the model (`HasUuids`) and unique/NOT NULL at DB level:
 *
 *  - `products.id` is dropped; `products.uuid` becomes `NOT NULL PRIMARY KEY`.
 *  - Every child `product_id` foreign key is converted from bigint to the
 *    UUID of its product and re-pointed to `products(uuid)` with the original
 *    delete rules (product_variants, product_images, cart_items, order_items,
 *    wishlist_items, coupon_product, reviews).
 *  - `stock_movements.stockable_id` (polymorphic morph column) is widened
 *    to hold UUIDs and existing product movements are re-linked by UUID.
 *  - Existing integer ids are resolved into their UUIDs during migration (data
 *    is preserved, not truncated).
 *
 * Written per supported driver (PostgreSQL, MySQL, SQLite) because PK/FK
 * surgery differs per engine. The `Product` model keeps an `id` accessor that maps
 * to the UUID, so `$product->id` keeps working unchanged (see app/Models/Product.php).
 */
return new class extends Migration
{
    /**
     * Child tables sharing a `product_id` foreign key to `products`.
     *
     * @var array<string, array{nullable: bool, on_delete: string, single_index: bool}>
     */
    private const CHILDREN = [
        'product_variants' => ['nullable' => false, 'on_delete' => 'cascade', 'single_index' => true],
        'product_images' => ['nullable' => false, 'on_delete' => 'cascade', 'single_index' => true],
        'cart_items' => ['nullable' => false, 'on_delete' => 'cascade', 'single_index' => true],
        'order_items' => ['nullable' => true,  'on_delete' => 'set_null', 'single_index' => true],
        'wishlist_items' => ['nullable' => true,  'on_delete' => 'set_null', 'single_index' => false],
        'coupon_product' => ['nullable' => false, 'on_delete' => 'cascade', 'single_index' => true],
        'reviews' => ['nullable' => false, 'on_delete' => 'cascade', 'single_index' => false],
    ];

    public function up(): void
    {
        match (DB::connection()->getDriverName()) {
            'pgsql' => $this->upPostgres(),
            'mysql' => $this->upMySql(),
            'sqlite' => $this->upSqlite(),
            default => throw new RuntimeException('Unsupported driver for the products UUID primary key migration.'),
        };
    }

    public function down(): void
    {
        match (DB::connection()->getDriverName()) {
            'pgsql' => $this->downPostgres(),
            'mysql' => $this->downMySql(),
            'sqlite' => $this->downSqlite(),
            default => throw new RuntimeException('Unsupported driver for the products UUID primary key rollback.'),
        };
    }

    /** Run an optional statement, ignoring "already missing" style errors. */
    private function tryStatement(string $sql): void
    {
        try {
            DB::statement($sql);
        } catch (Throwable) {
            // Intentionally swallowed: constraint/index/column may already be gone.
        }
    }

    /* -------------------------------------------------------------------------
     | PostgreSQL — up
     | ------------------------------------------------------------------------ */

    private function upPostgres(): void
    {
        foreach (self::CHILDREN as $table => $cfg) {
            // 1) Add a temporary UUID-typed column and resolve old int ids.
            $this->tryStatement("alter table {$table} add column product_uuid uuid;");
            $this->tryStatement(
                "update {$table} child set product_uuid = products.uuid
                 from products
                 where products.id = child.product_id
                   and child.product_id is not null"
            );

            if (! $cfg['nullable']) {
                // 2) Prune orphans (already hard-deleted parents) so the FK re-add asks.

                $this->tryStatement(
                    "delete from {$table} child
                     where child.product_id is not null
                       and not exists (select 1 from products where products.id = child.product_id)"
                );
            }

            // 3) Drop the legacy FK / indexes / column and rename the UUID column in.

            $this->tryStatement("alter table {$table} drop constraint if exists {$table}_product_id_foreign;");
            if ($cfg['single_index']) {
                $this->tryStatement("drop index if exists {$table}_product_id_index;");
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product drop constraint if exists coupon_product_pkey;');
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('drop index if exists wishlist_items_wishlist_id_product_id_index;');
            }
            if ($table === 'reviews') {
                $this->tryStatement('drop index if exists reviews_product_id_status_index;');
                $this->tryStatement('drop index if exists reviews_user_id_product_id_index;');
            }

            $this->tryStatement("alter table {$table} drop column if exists product_id;");
            $this->tryStatement("alter table {$table} rename column product_uuid to product_id;");
            $this->tryStatement("alter table {$table} alter column product_id type uuid using product_id::text::uuid;");
        }

        // 4) Widen the morph column so it can hold UUIDs, then re-link products.

        $this->tryStatement('alter table stock_movements alter column stockable_id type varchar(36) using stockable_id::text;');
        $this->tryStatement(
            "update stock_movements movement
             set stockable_id = products.uuid
             from products
             where movement.stockable_type = 'App\\Models\\Product'
               and movement.stockable_id ~ '^[0-9]+$'
               and movement.stockable_id::bigint = products.id"
        );

        // 5) Re-create indexes / FK constraints pointing at products(uuid). The
        //    old `products.uuid` unique index still exists, so the FK is accepted.

        foreach (self::CHILDREN as $table => $cfg) {

            $onDelete = $cfg['on_delete'] === 'cascade' ? 'cascade' : 'set null';

            if (! $cfg['nullable']) {
                $this->tryStatement("alter table {$table} alter column product_id set not null;");
            }
            if ($cfg['single_index']) {
                $this->tryStatement("create index {$table}_product_id_index on {$table} (product_id);");
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('create index wishlist_items_wishlist_id_product_id_index on wishlist_items (wishlist_id, product_id);');
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product add primary key (coupon_id, product_id);');
            }
            if ($table === 'reviews') {
                $this->tryStatement('create index reviews_product_id_status_index on reviews (product_id, status);');
                $this->tryStatement('create index reviews_user_id_product_id_index on reviews (user_id, product_id);');
            }

            $this->tryStatement(
                "alter table {$table} add constraint {$table}_product_id_foreign
                 foreign key (product_id) references products (uuid) on delete {$onDelete};"
            );
        }

        $this->upSwapProductsPostgres();
    }

    private function upSwapProductsPostgres(): void
    {
        // Nothing references products.id anymore — swap the key itself. The old
        // products.uuid unique index (which the child FKs rely on) is kept while
        // the new PRIMARY KEY is added; only then is the redundant index dropped.

        $this->tryStatement('alter table products alter column uuid set not null;');
        $this->tryStatement('alter table products add primary key (uuid);');
        $this->tryStatement('alter table products drop column id;');
        $this->tryStatement('drop sequence if exists products_id_seq;');
        $this->tryStatement('drop index if exists products_uuid_unique;');
    }

    /* -------------------------------------------------------------------------
     | MySQL — up
     | ------------------------------------------------------------------------ */

    private function upMySql(): void
    {
        foreach (self::CHILDREN as $table => $cfg) {
            $this->tryStatement("alter table {$table} add column product_uuid char(36) null;");
            $this->tryStatement(
                "update {$table} child
                 join products on products.id = child.product_id
                 set child.product_uuid = products.uuid
                 where child.product_id is not null"
            );

            if (! $cfg['nullable']) {
                $this->tryStatement(
                    "delete child from {$table} child
                     where child.product_id is not null
                       and not exists (select 1 from products where products.id = child.product_id)"
                );
            }

            $this->tryStatement("alter table {$table} drop foreign key {$table}_product_id_foreign;");
            if ($cfg['single_index']) {
                $this->tryStatement("alter table {$table} drop index {$table}_product_id_index;");
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product drop primary key;');
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('alter table wishlist_items drop index wishlist_items_wishlist_id_product_id_index;');
            }
            if ($table === 'reviews') {
                $this->tryStatement('alter table reviews drop index reviews_product_id_status_index;');
                $this->tryStatement('alter table reviews drop index reviews_user_id_product_id_index;');
            }

            $this->tryStatement("alter table {$table} drop column product_id;");
            $this->tryStatement("alter table {$table} change column product_uuid product_id char(36) null;");
            if (! $cfg['nullable']) {
                $this->tryStatement("alter table {$table} modify product_id char(36) not null;");
            }
        }

        // Morph column widens to varchar; then products are re-linked by UUID.

        $this->tryStatement('alter table stock_movements modify stockable_id varchar(36) null;');
        $this->tryStatement(
            "update stock_movements movement
             join products on cast(movement.stockable_id as unsigned) = products.id
             set movement.stockable_id = products.uuid
             where movement.stockable_type = 'App\\Models\\Product'
               and movement.stockable_id regexp '^[0-9]+$'"
        );

        foreach (self::CHILDREN as $table => $cfg) {
            $onDelete = $cfg['on_delete'] === 'cascade' ? 'cascade' : 'set null';

            if ($cfg['single_index']) {
                $this->tryStatement("create index {$table}_product_id_index on {$table} (product_id);");
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('create index wishlist_items_wishlist_id_product_id_index on wishlist_items (wishlist_id, product_id);');
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product add primary key (coupon_id, product_id);');
            }
            if ($table === 'reviews') {
                $this->tryStatement('create index reviews_product_id_status_index on reviews (product_id, status);');
                $this->tryStatement('create index reviews_user_id_product_id_index on reviews (user_id, product_id);');
            }

            $this->tryStatement(
                "alter table {$table} add constraint {$table}_product_id_foreign
                 foreign key (product_id) references products (uuid) on delete {$onDelete};"
            );
        }

        $this->upSwapProductsMySql();
    }

    private function upSwapProductsMySql(): void
    {
        // The child FKs to products(uuid) rely on the unique index; after the PK
        // on uuid is added, the old unique index is redundant and can go.
        $this->tryStatement('alter table products modify id bigint unsigned not null;');
        $this->tryStatement('alter table products drop primary key;');
        $this->tryStatement('alter table products drop column id;');
        $this->tryStatement('alter table products modify uuid char(36) not null;');
        $this->tryStatement('alter table products add primary key (uuid);');
        $this->tryStatement('alter table products drop index products_uuid_unique;');
    }

    /* -------------------------------------------------------------------------
     | SQLite — up
     | ------------------------------------------------------------------------ */

    private function upSqlite(): void
    {
        // The morph re-link must run while products still carries the integer
        // id column, before upSqliteProducts() drops it.
        $this->upSqliteStockMorph();
        $this->upSqliteProducts();
        $this->upSqliteChildren();
    }

    private function sqliteColumns(string $table): array
    {
        $safe = str_replace('"', '""', $table);

        return collect(DB::select('pragma table_info("'.$safe.'")'))->map(
            fn (object $col) => [
                'name' => $col->name,
                'type' => $col->type,
                'notnull' => (bool) $col->notnull,
                'default' => $col->dflt_value,
            ]
        )->all();
    }

    /** Capture named indexes (unique/plain, single/composite) before a table is dropped. */
    private function sqliteCaptureIndexes(string $table): array
    {
        $indexes = [];

        foreach (DB::select('pragma index_list("'.str_replace('"', '""', $table).'"")') as $index) {
            if (str_starts_with((string) $index->name, 'sqlite_autoindex_')) {
                continue;
            }

            $columns = collect(DB::select('pragma index_info("'.str_replace('"', '""', $index->name).'"")'))
                ->sortBy('seqno')
                ->map(fn (object $col) => '"'.$col->name.'"')
                ->implode(', ');

            $indexes[] = [
                'name' => $index->name,
                'columns' => $columns,
                'unique' => (bool) ($index->unique ?? 0),
            ];
        }

        return $indexes;
    }

    private function sqliteCreateIndexes(string $table, array $indexes): void
    {
        foreach ($indexes as $index) {
            $unique = $index['unique'] ? 'unique ' : '';
            $this->tryStatement(
                'create '.$unique.'index "'.str_replace('"', '""', $index['name']).'" on "'.$table.'" ('.$index['columns'].')'
            );
        }
    }

    private function upSqliteProducts(): void
    {
        $cols = array_values(array_filter($this->sqliteColumns('products'), fn (array $c) => $c['name'] !== 'id'));
        $indexes = $this->sqliteCaptureIndexes('products');

        $defs = [];
        foreach ($cols as $col) {
            if ($col['name'] === 'uuid') {
                $defs[] = '"uuid" char(36) not null primary key';

                continue;
            }
            $defs[] = '"'.str_replace('"', '""', $col['name']).'" '.$col['type'].
                ($col['notnull'] ? ' not null' : '').
                ($col['default'] !== null ? ' default '.$col['default'] : '');
        }
        $defs[] = 'foreign key ("category_id") references "categories" ("id") on delete set null';
        $defs[] = 'foreign key ("brand_id") references "brands" ("id") on delete set null';

        $columns = implode(', ', collect($cols)->map(fn (array $c) => '"'.$c['name'].'"')->all());

        DB::statement('create table "products_new" ('.implode(', ', $defs).')');
        DB::statement('insert into "products_new" ('.$columns.') select '.$columns.' from "products"');
        DB::statement('drop table "products"');
        $this->sqliteCreateIndexes('products_new', $indexes);
        DB::statement('alter table "products_new" rename to "products"');
    }

    private function upSqliteChildren(): void
    {
        foreach (self::CHILDREN as $table => $cfg) {
            // Orphan rows in NOT NULL children would violate the rebuilt NOT NULL column.

            if (! $cfg['nullable']) {
                $this->tryStatement(
                    'delete from "'.$table.'" where "product_id" is not null
                     and "product_id" not in (select "id" from "products")'
                );
            }

            $cols = $this->sqliteColumns($table);
            $indexes = $this->sqliteCaptureIndexes($table);

            $defs = [];
            foreach ($cols as $col) {
                if ($col['name'] === 'id') {
                    $defs[] = '"id" integer primary key autoincrement';

                    continue;
                }
                if ($col['name'] === 'product_id') {
                    $defs[] = '"product_id" char(36)'.($cfg['nullable'] ? '' : ' not null');

                    continue;
                }
                $defs[] = '"'.str_replace('"', '""', $col['name']).'" '.$col['type'].
                    ($col['notnull'] ? ' not null' : '').
                    ($col['default'] !== null ? ' default '.$col['default'] : '');
            }
            $defs[] = 'foreign key ("product_id") references "products" ("uuid") on delete '.($cfg['on_delete'] === 'cascade' ? 'cascade' : 'set null');

            $columns = collect($cols)->map(fn (array $c) => '"'.$c['name'].'"')->all();
            $selects = collect($cols)->map(fn (array $c) => $c['name'] === 'product_id' ? 'products."uuid"' : '"'.$c['name'].'"')->all();

            DB::statement('create table "'.$table.'_new" ('.implode(', ', $defs).')');
            DB::statement(
                'insert into "'.$table.'_new" ('.implode(', ', $columns).') select '.implode(', ', $selects).
                ' from "'.$table.'" left join "products" on "'.$table.'"."product_id" = "products"."id"'
            );
            DB::statement('drop table "'.$table.'"');
            $this->sqliteCreateIndexes($table.'_new', $indexes);
            DB::statement('alter table "'.$table.'_new" rename to "'.$table.'"');
        }
    }

    private function upSqliteStockMorph(): void
    {
        $this->tryStatement(
            "update \"stock_movements\" set \"stockable_id\" = (select \"uuid\" from \"products\" where cast(\"stock_movements\".\"stockable_id\" as integer) = \"products\".\"id\")
             where \"stock_movements\".\"stockable_type\" = 'App\\Models\\Product'
               and \"stock_movements\".\"stockable_id\" is not null
                 and typeof(\"stock_movements\".\"stockable_id\")in ('integer', 'real')"
        );
    }

    /* -------------------------------------------------------------------------
     | Down — PostgreSQL
     | ------------------------------------------------------------------------ */

    private function downPostgres(): void
    {
        // 1) Children: drop the FK to products(uuid) first — it would block
        //    dropping the uuid PK during the products swap below.

        foreach (self::CHILDREN as $table => $cfg) {
            $this->tryStatement("alter table {$table} drop constraint if exists {$table}_product_id_foreign;");
            if ($cfg['single_index']) {
                $this->tryStatement("drop index if exists {$table}_product_id_index;");
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product drop constraint if exists coupon_product_pkey;');
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('drop index if exists wishlist_items_wishlist_id_product_id_index;');
            }
            if ($table === 'reviews') {
                $this->tryStatement('drop index if exists reviews_product_id_status_index;');
                $this->tryStatement('drop index if exists reviews_user_id_product_id_index;');
            }
        }

        // 2) Swap products back: uuid PK → auto-increment id PK.

        $this->tryStatement('alter table products drop constraint if exists products_pkey;');
        $this->tryStatement('alter table products add column id bigserial;');
        $this->tryStatement('alter table products add primary key (id);');
        $this->tryStatement('alter table products alter column uuid drop not null;');
        $this->tryStatement('create unique index products_uuid_unique on products (uuid);');

        // 3) Re-link children + morph column back to the integer products ids.

        $this->downChildrenPostgres();
        $this->downStockMorphPostgres();
    }

    private function downChildrenPostgres(): void
    {
        foreach (self::CHILDREN as $table => $cfg) {
            // 1) Re-link values: UUID → auto-increment id.

            $this->tryStatement("alter table {$table} add column product_id_new bigint;");
            $this->tryStatement(
                "update {$table} child set product_id_new = products.id
                 from products
                 where products.uuid = child.product_id
                   and child.product_id is not null"
            );

            // 2) Drop the UUID column / indexes / FK pointing at products(uuid).

            $this->tryStatement("alter table {$table} drop constraint if exists {$table}_product_id_foreign;");
            if ($cfg['single_index']) {
                $this->tryStatement("drop index if exists {$table}_product_id_index;");
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product drop constraint if exists coupon_product_pkey;');
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('drop index if exists wishlist_items_wishlist_id_product_id_index;');
            }
            if ($table === 'reviews') {
                $this->tryStatement('drop index if exists reviews_product_id_status_index;');
                $this->tryStatement('drop index if exists reviews_user_id_product_id_index;');
            }

            $this->tryStatement("alter table {$table} drop column if exists product_id;");
            $this->tryStatement("alter table {$table} rename column product_id_new to product_id;");
            if (! $cfg['nullable']) {
                $this->tryStatement("alter table {$table} alter column product_id set not null;");
            }

            // 3) Rebuild indexes / FK against products(id) with the original rules.

            $onDelete = $cfg['on_delete'] === 'cascade' ? 'cascade' : 'set null';

            if ($cfg['single_index']) {
                $this->tryStatement("create index {$table}_product_id_index on {$table} (product_id);");
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('create index wishlist_items_wishlist_id_product_id_index on wishlist_items (wishlist_id, product_id);');
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product add primary key (coupon_id, product_id);');
            }
            if ($table === 'reviews') {
                $this->tryStatement('create index reviews_product_id_status_index on reviews (product_id, status);');
                $this->tryStatement('create index reviews_user_id_product_id_index on reviews (user_id, product_id);');
            }

            $this->tryStatement(
                "alter table {$table} add constraint {$table}_product_id_foreign
                 foreign key (product_id) references products (id) on delete {$onDelete};"
            );
        }
    }

    private function downStockMorphPostgres(): void
    {
        $this->tryStatement(
            "update stock_movements movement
             set stockable_id = products.id
             from products
             where movement.stockable_type = 'App\\Models\\Product'
               and movement.stockable_id = products.uuid"
        );
        $this->tryStatement(
            'alter table stock_movements alter column stockable_id type bigint using stockable_id::bigint;'
        );
    }

    /* -------------------------------------------------------------------------
     | Down — MySQL
     | ------------------------------------------------------------------------ */

    private function downMySql(): void
    {
        // 1) Children: drop FKs to products(uuid) so the products.id swap is free.

        foreach (self::CHILDREN as $table => $cfg) {
            $this->tryStatement("alter table {$table} drop foreign key {$table}_product_id_foreign;");
            if ($cfg['single_index']) {
                $this->tryStatement("alter table {$table} drop index {$table}_product_id_index;");
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product drop primary key;');
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('alter table wishlist_items drop index wishlist_items_wishlist_id_product_id_index;');
            }
            if ($table === 'reviews') {
                $this->tryStatement('alter table reviews drop index reviews_product_id_status_index;');
                $this->tryStatement('alter table reviews drop index reviews_user_id_product_id_index;');
            }
        }

        // 2) Swap products back to the auto-increment id PK.

        $this->tryStatement('alter table products modify uuid char(36) null;');
        $this->tryStatement('alter table products drop primary key;');
        $this->tryStatement('alter table products add column id bigint unsigned not null auto_increment, add primary key (id);');
        $this->tryStatement('alter table products add unique index products_uuid_unique (uuid);');

        // 3) Children: UUID values re-linked back to the integer products ids.

        foreach (self::CHILDREN as $table => $cfg) {
            $this->tryStatement("alter table {$table} add column product_id_new bigint null;");
            $this->tryStatement(
                "update {$table} child
                 join products on products.uuid = child.product_id
                 set child.product_id_new = products.id
                 where child.product_id is not null"
            );

            $this->tryStatement("alter table {$table} drop foreign key {$table}_product_id_foreign;");
            if ($cfg['single_index']) {
                $this->tryStatement("alter table {$table} drop index {$table}_product_id_index;");
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product drop primary key;');
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('alter table wishlist_items drop index wishlist_items_wishlist_id_product_id_index;');
            }
            if ($table === 'reviews') {
                $this->tryStatement('alter table reviews drop index reviews_product_id_status_index;');
                $this->tryStatement('alter table reviews drop index reviews_user_id_product_id_index;');
            }

            $this->tryStatement("alter table {$table} drop column product_id;");
            $this->tryStatement("alter table {$table} change column product_id_new product_id bigint null;");
            if (! $cfg['nullable']) {
                $this->tryStatement("alter table {$table} modify product_id bigint not null;");
            }

            $onDelete = $cfg['on_delete'] === 'cascade' ? 'cascade' : 'set null';

            if ($cfg['single_index']) {
                $this->tryStatement("create index {$table}_product_id_index on {$table} (product_id);");
            }
            if ($table === 'wishlist_items') {
                $this->tryStatement('create index wishlist_items_wishlist_id_product_id_index on wishlist_items (wishlist_id, product_id);');
            }
            if ($table === 'coupon_product') {
                $this->tryStatement('alter table coupon_product add primary key (coupon_id, product_id);');
            }
            if ($table === 'reviews') {
                $this->tryStatement('create index reviews_product_id_status_index on reviews (product_id, status);');
                $this->tryStatement('create index reviews_user_id_product_id_index on reviews (user_id, product_id);');
            }

            $this->tryStatement(
                "alter table {$table} add constraint {$table}_product_id_foreign
                 foreign key (product_id) references products (id) on delete {$onDelete};"
            );
        }

        // 2) Morph column back to unsigned bigint values mapped to integer ids.

        $this->tryStatement(
            "update stock_movements movement
             join products on products.uuid = movement.stockable_id
             set movement.stockable_id = products.id
             where movement.stockable_type = 'App\\Models\\Product'"
        );
        $this->tryStatement('alter table stock_movements modify stockable_id bigint unsigned null;');
    }

    /* -------------------------------------------------------------------------
     | Down — SQLite
     | ------------------------------------------------------------------------ */

    private function downSqlite(): void
    {
        $this->downSqliteProducts();
        $this->downSqliteChildren();
        $this->downSqliteStockMorph();
    }

    private function downSqliteProducts(): void
    {
        $cols = $this->sqliteColumns('products');
        $indexes = $this->sqliteCaptureIndexes('products');

        $defs = ['"id" integer primary key autoincrement'];
        foreach ($cols as $col) {
            if ($col['name'] === 'uuid') {
                $defs[] = '"uuid" varchar(36)';

                continue;
            }
            $defs[] = '"'.str_replace('"', '""', $col['name']).'" '.$col['type'].
                ($col['notnull'] ? ' not null' : '').
                ($col['default'] !== null ? ' default '.$col['default'] : '');
        }
        $defs[] = 'foreign key ("category_id") references "categories" ("id") on delete set null';
        $defs[] = 'foreign key ("brand_id") references "brands" ("id") on delete set null';

        $columns = implode(', ', collect($cols)->map(fn (array $c) => '"'.$c['name'].'"')->all());

        DB::statement('create table "products_new" ('.implode(', ', $defs).')');
        DB::statement('insert into "products_new" ('.$columns.') select '.$columns.' from "products"');
        DB::statement('drop table "products"');

        $indexes[] = ['name' => 'products_uuid_unique', 'columns' => '"uuid"', 'unique' => true];
        $this->sqliteCreateIndexes('products_new', $indexes);
        DB::statement('alter table "products_new" rename to "products"');
    }

    private function downSqliteChildren(): void
    {
        foreach (self::CHILDREN as $table => $cfg) {
            $cols = $this->sqliteColumns($table);
            $indexes = $this->sqliteCaptureIndexes($table);

            $defs = [];
            foreach ($cols as $col) {
                if ($col['name'] === 'id') {
                    $defs[] = '"id" integer primary key autoincrement';

                    continue;
                }
                if ($col['name'] === 'product_id') {
                    $defs[] = '"product_id" integer'.($cfg['nullable'] ? '' : ' not null');

                    continue;
                }
                $defs[] = '"'.str_replace('"', '""', $col['name']).'" '.$col['type'].
                    ($col['notnull'] ? ' not null' : '').
                    ($col['default'] !== null ? ' default '.$col['default'] : '');
            }
            $defs[] = 'foreign key ("product_id") references "products" ("id") on delete '.($cfg['on_delete'] === 'cascade' ? 'cascade' : 'set null');

            $columns = collect($cols)->map(fn (array $c) => '"'.$c['name'].'"')->all();
            $selects = collect($cols)->map(fn (array $c) => $c['name'] === 'product_id' ? 'products."id"' : '"'.$c['name'].'"')->all();

            DB::statement('create table "'.$table.'_new" ('.implode(', ', $defs).')');
            DB::statement(
                'insert into "'.$table.'_new" ('.implode(', ', $columns).') select '.implode(', ', $selects).
                ' from "'.$table.'" left join "products" on "'.$table.'"."product_id" = "products"."uuid"'
            );
            DB::statement('drop table "'.$table.'"');
            $this->sqliteCreateIndexes($table.'_new', $indexes);
            DB::statement('alter table "'.$table.'_new" rename to "'.$table.'"');
        }
    }

    private function downSqliteStockMorph(): void
    {
        // SQLite re-link: map UUID values back to the integer ids before the products swap.
        $this->tryStatement(
            'update stock_movements set stockable_id = (select id from products where products.uuid = stock_movements.stockable_id)'
            ." where stockable_type = 'App\\Models\\Product'"
            .' and stockable_id in (select uuid from products)'
        );
    }
};
