<?php

namespace App\Models;

use App\Models\Concerns\TracksInventory;
use App\Services\AdminNotificationService;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use HasFactory, HasUuids, SoftDeletes, TracksInventory;

    /** The public product id is a UUID generated by HasUuids. */
    protected $primaryKey = 'id';

    public $incrementing = false;

    protected $keyType = 'string';

    /**
     * Column(s) that receive an auto-generated UUID on create (HasUuids).
     *
     * @return list<string>
     */
    public function uniqueIds(): array
    {
        return ['id'];
    }

    protected $fillable = [
        'category_id',
        'brand_id',
        'name',
        'slug',
        'sku',
        'barcode',
        'short_description',
        'description',
        'price',
        'sale_price',
        'cost_price',
        'stock_quantity',
        'reserved_stock',
        'damaged_stock',
        'incoming_stock',
        'min_stock_alert',
        'max_stock_level',
        'reorder_point',
        'track_inventory',
        'in_stock',
        'warehouse_location',
        'weight',
        'length',
        'width',
        'height',
        'thumbnail',
        'meta_title',
        'meta_description',
        'is_active',
        'is_featured',
        'is_digital',
        'views_count',
        'sales_count',
        'sort_order',
        'version',
    ];

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function variants()
    {
        // Explicit foreign key keeps the UUID product id contract clear.
        return $this->hasMany(ProductVariant::class, 'product_id');
    }

    /**
     * The product's image gallery, in the order the storefront should show it.
     *
     * Ordered on the relation rather than at the call site so every eager load
     * (`with('images')`, `load('images')`) gets the same sequence — the primary
     * image is not guaranteed to be sort_order 0, so it is not sorted first
     * here; consumers pick it out via `is_primary`.
     */
    public function images()
    {
        // Explicit foreign key for the UUID product id.
        return $this->hasMany(ProductImage::class, 'product_id')
            ->orderBy('sort_order')
            ->orderBy('id');
    }

    public function stockMovements()
    {
        // Explicit morph keys keep the product id column name stable.
        return $this->morphMany(StockMovement::class, 'stockable', 'stockable_type', 'stockable_id');
    }

    /**
     * Promotions applied to this product.
     *
     * Backed by `Coupon`, not `Promotion`: the admin promotions API
     * (PromotionController) reads and writes coupons, so those are the rows the
     * product form offers. Soft-deleted coupons are excluded so a deleted
     * promotion stops applying without needing the pivot row cleaned up.
     */
    public function promotions(): BelongsToMany
    {
        // Explicit pivot keys use the product id column.
        return $this->belongsToMany(Coupon::class, 'coupon_product', 'product_id', 'coupon_id')
            ->whereNull('coupons.deleted_at');
    }

    public static function booted(): void
    {
        static::saving(function (self $product) {
            $product->version++;
        });

        static::saved(function (self $product): void {
            if (! $product->wasChanged('stock_quantity') || ! $product->track_inventory) {
                return;
            }

            $previousQuantity = (int) $product->getOriginal('stock_quantity');
            $newQuantity = (int) $product->stock_quantity;
            DB::afterCommit(fn () => app(AdminNotificationService::class)
                ->inventoryStatus($product, $previousQuantity, $newQuantity));
        });
    }

    public function scopeLowStock($query)
    {
        return $query->whereColumn('stock_quantity', '<=', 'min_stock_alert');
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeOutOfStock($query)
    {
        return $query->where(function ($q) {
            $q->where('stock_quantity', '<=', 0)
                ->orWhere('in_stock', false);
        });
    }

    public function scopeByCategory($query, $categoryId)
    {
        return $query->where('category_id', $categoryId);
    }

    public function getStockValueAttribute()
    {
        return (int) $this->stock_quantity * (float) $this->cost_price;
    }
}
